version: "3.8"
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: legalindia
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  backend:
    image: ghcr.io/raghavaaa/lindia-b:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://local:local@postgres:5432/legalindia
      REDIS_URL: redis://redis:6379
      JWT_SECRET: changeme
      LOG_LEVEL: info
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:

