# LegalIndia Infrastructure - Railway Configuration
# Project: lindia-in
# Services: infra-layer, backend, database

[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
healthcheckPath = "/health"
healthcheckTimeout = 100

[environments.production]
# Production deployment settings
replicas = 1

[environments.staging]
# Staging deployment settings
replicas = 1
