name: Deploy Backend & Database

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install requests pytest

      - name: Run basic smoke test
        run: echo "Running infra smoke tests..." && pytest || true

      - name: Deploy via Railway CLI
        env:
          RAILWAY_API_KEY: ${{ secrets.RAILWAY_API_KEY }}
        run: |
          npm install -g @railway/cli
          railway up --service backend

